### ISSUE TITLE
Some missing TOC and DAG Lump Hashes

### ISSUE THREAD

**Issue by neptuwunium** [chaoticgd/ripped_apart#1]
Archive TOC

```
65bcf461 Archive TOC Asset Metadata
398abff0 Archive TOC File Metadata
ede8ada9 Archive TOC Header
36a6c8cc Archive TOC Texture Asset Ids
62297090 Archive TOC Texture Header
c9fb9dda Archive TOC Texture Meta
```
still missing 0x506d7b8a and 0x654bded9

Dependency DAG

```
bc91d1cc Dependency Links
f958372e Dependency Links Heads
```
still missing 0xbfec699f

**Comment by chaoticgd** [comment]
Thanks!

Found that 506d7b8a is "Archive TOC Asset IDs".

**Comment by chaoticgd** [comment]
I noticed you're also working on tools for these games. I'm in two discord servers for modding the R&C games if you're interested:
https://discord.com/invite/smpcmodding - Spiderman modding server. Same engine, so lots of people there familiar with modding Insomniac's newer games.
https://discord.gg/FY4Gwv8EuK - The R&C modding server. A lot of people there are more focused on the PS2 games, but there is also work on the PS3/PS4/PS5 games.

**Comment by chaoticgd** [comment]
And I've found that 654bded9 is "Archive TOC Asset Header Data".

**Comment by neptuwunium** [comment]
Awesome. It's nice to have a full set of known hashes.

**Comment by neptuwunium** [comment]
Closing as I see you have updated the code with the new lump names.

**Comment by neptuwunium** [comment]
Oh, by the way. All of the hashes I've found are here: https://github.com/yretenai/rivet/blob/develop/docs/dat1_hashes_known.txt

There are no doubt a few false positives in here (like `1f6a31a6 Map Data` and `a59f667b Material Template Constants Content` are suspect)
